FROM python:3.10

WORKDIR ~/Documents/BeCode/becode_projects/real-estate-price-prediction/Deployment
RUN mkdir /app

COPY /requirements.txt /app/requirements.txt
COPY /predict.py /app/predict.py
COPY /callAPI.py /app/callAPI.py
COPY /App.py /app/App.py
COPY /appt_pred_model.pkl /app/appt_pred_model.pkl
COPY /house_pred_model.pkl /app/house_pred_model.pkl

WORKDIR /app
RUN pip install -r requirements.txt





